### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by Ichigoo** [junkboy0315/pairwise-pict-online#10]
Hello, 

  First, Thank you for this helpful project, it helped me a lot.

  Today I encountered with this problem where I tray to generate my data combinations, when I click generate it starts calculating but in the end I receive this message "Failed to fetch".
If I enter my data without adding conditions it works but when I do add I get the error, maybe because my condition is pretty long, I don't if there is a length limit for writing conditions or not.

  I hope someone can clear this up for me.

  Thank you.

**Comment by tam315** [comment]
Hi, @Ichigoo ,Thanks for feedback.
If you don't mind, could you provide a source txt?
I'll check it out.

**Comment by Ichigoo** [comment]
Thank you for the fast response, I sent you the text file through your email.

**Comment by Ichigoo** [comment]
any updates @junkboy0315 ?

**Comment by tam315** [comment]
Sorry, the mail was in junk-mail box.
Unfortunately, I found nothing helpful things.
Could you try official command line tool?
https://github.com/microsoft/pict

**Comment by Ichigoo** [comment]
Hello,
Yeah I tried the official tool, when I insert my script, it just keeps
loading, no result.
